"""Add blog posts

Revision ID: 31a3bc4eb613
Revises: 
Create Date: 2025-11-09 14:07:02.248752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31a3bc4eb613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Clean up any leftover temporary tables first
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_blog_posts')
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_blog_comments')
    op.execute('DROP TABLE IF EXISTS _alembic_tmp_products')
    
    # Add missing author_id column to blog_posts
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.create_foreign_key('fk_blog_posts_author_id', 'users', ['author_id'], ['id'])



    # Add missing columns to products
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('in_stock', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('min_quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vendor_id', sa.Integer(), nullable=False, server_default='1'))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_products_vendor_id', 'users', ['vendor_id'], ['id'])

    # Recreate blog_comments table
    op.execute('ALTER TABLE blog_comments RENAME TO blog_comments_old')
    
    op.create_table('blog_comments',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('post_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('is_approved', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], name='fk_blog_comments_post_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_blog_comments_user_id'),
        sa.PrimaryKeyConstraint('id')
    )

    # Copy data from old table to new table
    op.execute('''
        INSERT INTO blog_comments (id, post_id, content, is_approved, created_at, user_id)
        SELECT id, post_id, content, is_approved, created_at, 1 FROM blog_comments_old
    ''')

    # Drop old table
    op.execute('DROP TABLE blog_comments_old')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blog_comments_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_blog_comments_author_id', 'users', ['author_id'], ['id'])
        
    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_blog_posts_author_id', type_='foreignkey')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_vendor_id', type_='foreignkey')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('is_active')
        batch_op.drop_column('vendor_id')
        batch_op.drop_column('min_quantity')
        batch_op.drop_column('quantity')
        batch_op.drop_column('in_stock')
        batch_op.drop_column('sub_category')

    with op.batch_alter_table('blog_posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    with op.batch_alter_table('blog_comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###
