"""Add customer fields

Revision ID: f1b0667b4fe9
Revises: 31a3bc4eb613
Create Date: 2025-11-10 15:40:03.901725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1b0667b4fe9'
down_revision = '31a3bc4eb613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('stock')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interests', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('preferred_contact', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('preferred_contact')
        batch_op.drop_column('interests')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
